CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_L_SBOCORREOS"
(
    IN vUSER_CODE NVARCHAR(50)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    SELECT IFNULL("E_Mail", '') AS "E_Mail"
    FROM "OUSR"
    WHERE "USER_CODE" = :vUSER_CODE;
END;
