CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_R_PLANILLA_TRANSFERENCIA_BY_PL"
(
    IN vPL NVARCHAR(50)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    DELETE FROM "@EXX_BCP_HOST" WHERE "U_HTH_PL" = :vPL AND "U_HTH_CA" = 'T';
    DELETE FROM "@EXX_BCP_TRAN" WHERE "U_HTH_PL" = :vPL;
    DELETE FROM "@EXX_BCP_TRAN_OVPM" WHERE "U_HTH_PL" = :vPL;
    DELETE FROM "@EXX_BCP_TRAN_CAR" WHERE "U_HTH_PL" = :vPL;
    DELETE FROM "@EXX_BCP_TRAN_ABO" WHERE "U_HTH_PL" = :vPL;
END;
