CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_L_TRANSFERENCIA_PAGOSOVPM"
(
    IN vPlanilla NVARCHAR(50)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    SELECT * FROM "@EXX_BCP_TRAN_OVPM" WHERE "U_HTH_PL" = :vPlanilla;
END;
