CREATE PROCEDURE "SP_EXX_BCP_A_RESUMEN_PAGO"
(
IN vCode NVARCHAR(50),
IN vName NVARCHAR(100),
IN vHTH_PL NVARCHAR(254),
IN vWIZNAME NVARCHAR(254),
IN vWIZFI NVARCHAR(20),
IN vWIZFF NVARCHAR(20),
IN vFECHA NVARCHAR(20)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    INSERT INTO "@EXX_BCP_PROV_PAGO"
               ("Code", "Name", "U_HTH_PL", "U_WIZNAME", "U_WIZFI", "U_WIZFF", "U_FECHA")
         VALUES
               (vCode, vName, vHTH_PL, vWIZNAME, vWIZFI, vWIZFF, vFECHA);
END;
