CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_D_HTH_PLANILLA_BY_PL"
(
IN vPL NVARCHAR(100),
IN vCA NVARCHAR(10)
)
LANGUAGE SQLSCRIPT
AS
BEGIN 
	IF vCA = 'P' THEN
		BEGIN
			DELETE FROM "@EXX_BCP_PROV_DOC" WHERE "U_HTH_PL" = vPL;
			DELETE FROM "@EXX_BCP_PROV_ABO" WHERE "U_HTH_PL" = vPL;
			DELETE FROM "@EXX_BCP_PROV_CAR" WHERE "U_HTH_PL" = vPL;
			DELETE FROM "@EXX_BCP_PROV_PAGO" WHERE "U_HTH_PL" = vPL;
			DELETE FROM "@EXX_BCP_HOST" WHERE "U_HTH_PL" = vPL AND "U_HTH_CA" = vCA;
		END;
	END IF;

	IF vCA = 'T' THEN
		BEGIN
			DELETE FROM "@EXX_BCP_TRAN_ABO" WHERE "U_HTH_PL" = vPL;
			DELETE FROM "@EXX_BCP_TRAN_CAR" WHERE "U_HTH_PL" = vPL;
			DELETE FROM "@EXX_BCP_TRAN_OVPM" WHERE "U_HTH_PL" = vPL;
			DELETE FROM "@EXX_BCP_TRAN" WHERE "U_HTH_PL" = vPL;
			DELETE FROM "@EXX_BCP_HOST" WHERE "U_HTH_PL" = vPL AND "U_HTH_CA" = vCA;
		END;
	END IF;
END;