CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_L_TRANSFERENCIA_ABONO"
(
    IN vPlanilla NVARCHAR(50)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    SELECT T0.* 
    FROM "@EXX_BCP_TRAN_ABO" T0 
    WHERE T0."U_HTT_CA" = :vPlanilla 
    ORDER BY T0."U_313_IA" ASC;
END;