CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_U_PLANILLA_RETORNOSFTP"
(
    IN vPL NVARCHAR(254),
    IN vNAD NVARCHAR(254),
    IN vNAR2 NVARCHAR(254),
    IN vPR NVARCHAR(254)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    UPDATE "@EXX_BCP_HOST"
    SET "U_HTH_NAD" = :vNAD,
        "U_HTH_NAR2" = :vNAR2,
        "U_HTH_PR" = :vPR
    WHERE "U_HTH_PL" = :vPL;
END;
