CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_L_PROVEEDOR_DOCUMENTO_BY_PLANILLA"
(
    IN vPlanilla NVARCHAR(254)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    SELECT * 
    FROM "@EXX_BCP_PROV_DOC"
    WHERE "U_HTA_PA" = :vPlanilla;
END;