CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_L_PLANILLA_BY_ACCION"
(
IN vCA NVARCHAR(10),
IN vPLG NVARCHAR(10)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    SELECT * FROM "@EXX_BCP_HOST" T0
    WHERE  T0."U_HTH_CA" = :vCA
    AND T0."U_HTH_PLG" = :vPLG
    AND IFNULL(T0."U_HTH_NAR2", '') = ''
    AND IFNULL(T0."U_HTH_NAD", '') = ''
    AND IFNULL(T0."U_HTH_COR", 'N') = 'N';
END;
