CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_R_PLANILLA_PROVEEDOR_BY_PL"
(
    IN vPL NVARCHAR(50)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    DELETE FROM "@EXX_BCP_HOST" WHERE "U_HTH_PL" = :vPL AND "U_HTH_CA" = 'P';
    DELETE FROM "@EXX_BCP_PROV_PAGO" WHERE "U_HTH_PL" = :vPL;
    DELETE FROM "@EXX_BCP_PROV_CAR" WHERE "U_HTH_PL" = :vPL;
    DELETE FROM "@EXX_BCP_PROV_ABO" WHERE "U_HTH_PL" = :vPL;
    DELETE FROM "@EXX_BCP_PROV_DOC" WHERE "U_HTH_PL" = :vPL;
END;
