CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_L_PLANILLA_NAR"
(
IN vCA NVARCHAR(10)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    SELECT * FROM "@EXX_BCP_HOST" T0
    WHERE  T0."U_HTH_CA" = :vCA
    AND T0."U_HTH_PLG" = 'G'
    AND T0."U_HTH_PR" = 'W'
    AND IFNULL(T0."U_HTH_NAR2", '') <> '';
END;
