CREATE PROCEDURE "SP_EXXIS_PLANILLA_BCP_L_HOST_BY_ACCION"  
(  
IN vHTH_PR NVARCHAR(1),  
IN vHTH_CA NVARCHAR(1),  
IN vFechaI NVARCHAR(10),  
IN vFechaF NVARCHAR(10)  
)  
LANGUAGE SQLSCRIPT  
AS  
BEGIN  
  
 SELECT '0' AS "Marcar", T0.* FROM "@EXX_BCP_HOST" T0   
 WHERE   
      T0."U_HTH_PR" = :vHTH_PR   
	  AND T0."U_HTH_CA" = :vHTH_CA  
      AND IFNULL(T0."U_HTH_PLG", 'P') NOT IN ('E', 'G');
   --AND TO_VARCHAR(T0."U_HTH_FC", 'DD.MM.YYYY') >= TO_VARCHAR(:vFechaI, 'DD.MM.YYYY')  
   --AND TO_VARCHAR(T0."U_HTH_FC", 'DD.MM.YYYY') <= TO_VARCHAR(:vFechaF, 'DD.MM.YYYY')  
END;
